// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-tickets.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tickets_default = defineTool({
  name: "list_tickets",
  title: "List clinic tickets",
  description: "List active tickets for the signed-in user's clinic. Returns id, patient name, phone, status, source, and created_at.",
  inputSchema: {
    status: z.string().optional().describe(
      "Optional status filter, e.g. INSIDE_WAITING, REMOTE_BOOKED, LINK_SENT, CALLED, IN_SERVICE, DONE, MISSED."
    ),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = sb(ctx);
    const { data: roles } = await supabase.from("user_roles").select("clinic_id").eq("user_id", ctx.getUserId());
    const clinicId = roles?.[0]?.clinic_id;
    if (!clinicId) {
      return { content: [{ type: "text", text: "No clinic for this user." }], isError: true };
    }
    let q = supabase.from("tickets").select("id, patient_name, patient_phone, status, source, created_at").eq("clinic_id", clinicId).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tickets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/call-next.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var call_next_default = defineTool2({
  name: "call_next",
  title: "Call next patient",
  description: "Call the next patient in the signed-in user's clinic queue.",
  inputSchema: {},
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = sb2(ctx);
    const { data: roles } = await supabase.from("user_roles").select("clinic_id").eq("user_id", ctx.getUserId());
    const clinicId = roles?.[0]?.clinic_id;
    if (!clinicId) {
      return { content: [{ type: "text", text: "No clinic for this user." }], isError: true };
    }
    const { data, error } = await supabase.rpc("call_next", { p_clinic_id: clinicId });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { result: data }
    };
  }
});

// src/lib/mcp/tools/clinic-info.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var clinic_info_default = defineTool3({
  name: "get_clinic_info",
  title: "Get clinic info",
  description: "Get the signed-in user's clinic: name, status, timezone, and current session flags (paused, intake open).",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = sb3(ctx);
    const { data: roles } = await supabase.from("user_roles").select("clinic_id").eq("user_id", ctx.getUserId());
    const clinicId = roles?.[0]?.clinic_id;
    if (!clinicId) {
      return { content: [{ type: "text", text: "No clinic for this user." }], isError: true };
    }
    const { data, error } = await supabase.from("clinics").select("id, name_ar, status, timezone, session_paused, intake_open").eq("id", clinicId).single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { clinic: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ecjvrfascepvfvxykccw";
var mcp_default = defineMcp({
  name: "inddd-clinic-mcp",
  title: "INDDD Clinic MCP",
  version: "0.1.0",
  instructions: "Tools for the INDDD clinic queue app. Use `get_clinic_info` to identify the clinic, `list_tickets` to inspect the queue, and `call_next` to call the next patient.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tickets_default, call_next_default, clinic_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
